name: CI/CD Pipeline - DEXMATE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-package-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (Build)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Create build artifact
        run: |
          zip -r build.zip src -x "*.pyc" "__pycache__/*"

      - name: Run unit tests
        run: |
          pytest -q

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-build
          path: build.zip

      - name: Simulated Deploy
        uses: actions/download-artifact@v4
        with:
          name: pokemon-build
          path: ./downloaded

      - name: Simulated Deploy - print message using DEPLOY_API_KEY
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        run: |
          echo "Downloaded files:"
          ls -la ./downloaded
          echo "Deployment using API Key: $DEPLOY_API_KEY"             

                







  
