name: build & Deploy

on:
   push:
         branches:
                 -main
env:
    CI: false
jobs:
  build:
  name: Build
  runs-on: ubuntu-latest
  -name: Checkout repo
  user: actions/checout@v2
  
-name: Setup Node
users: actions/setup-node@v1
with:
node-version: 16

-name: Install dependencies
users: bahmutov/npm-install@v1
-name: Build project
run: npm run build

-name: Upload production-ready build files
uses: actions/upload-artifact@v2
with:
name: Deploy
needs: build
runs-on: ubuntu-latest
if: github.ref == 'refs/heads/main'
steps:
-name: Download artifact
uses: aactions/download-artifact@v2
with:
name: production-files
path: ./build

-name: Deploy to GitHub Pages
uses: peaceiris/actions-gh-pages@v3
with:
github_token: ${{ secrets.TOKEN }}
publish_dir: ./build


  
